services:
  frontend:
    build: ./frontend
    container_name: ecommerce-frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

    restart: unless-stopped

  backend:
    build: ./backend
    container_name: ecommerce-backend

    ports:
      - "5001:5000"

    volumes:
      - ./backend:/app
      - /app/node_modules

    env_file:
      - ./backend/.env

    depends_on:
      mongodb:
        condition: service_started

      redis:
        condition: service_started

      elasticsearch:
        condition: service_healthy

    restart: unless-stopped

  mongodb:
    image: mongo:7

    container_name: ecommerce-mongodb

    command: ["mongod", "--replSet", "rs0"]

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

    restart: unless-stopped

  redis:
    image: redis:7
    container_name: ecommerce-redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: ecommerce-elasticsearch

    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    ports:
      - "9200:9200"

    volumes:
      - elastic-data:/usr/share/elasticsearch/data

    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 > /dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20

    restart: unless-stopped

volumes:
  mongo-data:
  redis-data:
  elastic-data: